--- #YAML:1.0
name:               Devel-SlowBless
version:            0.03
abstract:           Perl extension for identifying code that causes bless
author:
    - Benjamin Holzman <bholzman@earthlink.net>, Grant Street Group <developers@grantstreet.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
